server:
  port: PORT

spring:
  datasource:
    url: jdbc:mysql://YOUR_IP:3306/database?serverTimezone=GMT%2B8
    username: root
    password: password

swagger:
  production: false
  basic:
    enable: true
    username: account
    password: password